import React, { useEffect, useState } from 'react';
import {
  FaShieldAlt,
  FaFileContract,
  FaUserShield,
  FaGavel,
  FaBalanceScale,
  FaInfoCircle,
  FaCheckCircle,
  FaExternalLinkAlt,
  FaPhone,
  FaEnvelope,
  FaWhatsapp,
  FaPrint,
  FaDownload,
  FaChevronDown,
  FaChevronUp,
  FaSearch,
  FaBookOpen,
  FaUsers,
  FaUserLock,
  FaDatabase,
  FaGlobe,
  FaBuilding,
  FaRegClock,
  FaArrowRight
} from "react-icons/fa";
import { MdVerified, MdSecurity, MdGavel } from "react-icons/md";
import { Link } from 'react-router-dom';


const TermOffUse = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [searchTerm, setSearchTerm] = useState('');
  const [expandedSections, setExpandedSections] = useState({});

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const sections = [
    { id: 'overview', label: 'Overview', icon: FaInfoCircle },
    { id: 'membership', label: 'Membership', icon: FaUsers },
    { id: 'account', label: 'Account', icon: FaUserLock },
    { id: 'terms', label: 'Terms', icon: FaGavel }
  ];

  const toggleSection = (sectionId) => {
    setExpandedSections(prev => ({
      ...prev,
      [sectionId]: !prev[sectionId]
    }));
  };

  // Search functionality
  const filteredContent = (text) => {
    if (!searchTerm) return text;
    const regex = new RegExp(`(${searchTerm})`, 'gi');
    return text.replace(regex, '<mark class="bg-yellow-200 px-1 rounded">$1</mark>');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#E7E1B1] via-[#FBF5DD] to-[#E7E1B1] py-8 md:py-12">
      <div className="max-w-5xl mx-auto px-4 sm:px-6">
        
        {/* Header */}
        <div className="text-center mb-8 md:mb-10">
          <div className="inline-block relative">
            <div className="flex items-center justify-center gap-3 mb-2">
              <FaFileContract className="text-4xl text-[#306D29]" />
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold text-gray-800">
                Terms of Use
              </h1>
            </div>
            <span className="absolute -bottom-2 left-1/2 transform -translate-x-1/2 w-24 h-1 bg-gradient-to-r from-green-500 to-emerald-400 rounded-full"></span>
          </div>
          <p className="text-gray-600 mt-4 text-sm md:text-base max-w-2xl mx-auto">
            Please read these terms carefully before using our platform. By using our services, you agree to these terms.
          </p>
        </div>

        {/* Navigation Tabs */}
        <div className="bg-white/90 backdrop-blur-sm rounded-2xl shadow-xl p-1 mb-6 overflow-x-auto">
          <div className="flex flex-nowrap gap-1 min-w-max">
            {sections.map((section) => {
              const Icon = section.icon;
              const isActive = activeSection === section.id;
              return (
                <button
                  key={section.id}
                  onClick={() => setActiveSection(section.id)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl font-medium transition-all duration-300 whitespace-nowrap ${
                    isActive
                      ? 'bg-gradient-to-r from-[#306D29] to-[#4CAF50] text-white shadow-lg'
                      : 'text-gray-600 hover:bg-gray-100'
                  }`}
                >
                  <Icon className={`${isActive ? 'text-white' : 'text-gray-400'}`} />
                  <span className="text-sm">{section.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Main Content */}
        <div className="bg-white/90 backdrop-blur-sm rounded-3xl shadow-2xl p-6 md:p-8">
          
          {/* Disclaimer Banner */}
          <div className="bg-amber-50 rounded-xl p-4 mb-6 border-l-4 border-amber-500 flex items-start gap-3">
            <FaInfoCircle className="text-amber-500 text-xl flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-amber-800">
                <strong>Disclaimer:</strong> In case of any discrepancy or difference, the English version will take precedence over the translation.
              </p>
            </div>
          </div>

          {/* Electronic Record Notice */}
          <div className="bg-blue-50 rounded-xl p-4 mb-6 border border-blue-200">
            <div className="flex items-start gap-3">
              <MdVerified className="text-blue-500 text-xl flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="font-semibold text-blue-800 text-sm">Electronic Record</h4>
                <p className="text-sm text-blue-700 mt-1">
                  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. 
                  This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
              </div>
            </div>
          </div>

          {/* Content Sections */}
          <div className="space-y-6">
            
            {/* Section 1: Introduction */}
            <div className="border border-gray-200 rounded-xl overflow-hidden">
              <button
                onClick={() => toggleSection('intro')}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-1.5 bg-[#306D29]/10 rounded-lg">
                    <FaGlobe className="text-[#306D29]" />
                  </div>
                  <h3 className="font-semibold text-gray-800">Introduction</h3>
                </div>
                <span className="text-gray-400">
                  {expandedSections['intro'] ? <FaChevronUp /> : <FaChevronDown />}
                </span>
              </button>
              
              {expandedSections['intro'] && (
                <div className="p-4 space-y-3 text-gray-700 leading-relaxed animate-slideDown">
                  <p>
                    This document is published in accordance with the provisions of Rule 3 (1) of the 
                    Information Technology (Intermediaries guidelines) Rules, 2021 that require publishing 
                    the rules and regulations, privacy policy and Terms of Use for access or usage of 
                    domain name ("Website"), including the related mobile site and mobile application 
                    (hereinafter referred to as "Platform").
                  </p>
                  
                  <div className="bg-gray-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 flex items-center gap-2">
                      <FaBuilding className="text-[#306D29]" />
                      Platform Ownership
                    </h4>
                    <p className="text-sm text-gray-600 mt-1">
                      The Platform is owned by Glamorous Internet Private Limited, a company incorporated under 
                      the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, 
                      Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, 
                      Karnataka, India.
                    </p>
                  </div>

                  <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                    <p className="text-sm text-green-800">
                      <strong>Contracting Party:</strong> By mere use of the Platform, You shall be contracting 
                      with Flipkart Internet Private Limited and these terms and conditions including the policies 
                      constitute Your binding obligations.
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Section 2: Acceptance of Terms */}
            <div className="border border-gray-200 rounded-xl overflow-hidden">
              <button
                onClick={() => toggleSection('acceptance')}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-1.5 bg-green-100 rounded-lg">
                    <FaCheckCircle className="text-green-600" />
                  </div>
                  <h3 className="font-semibold text-gray-800">Acceptance of Terms</h3>
                </div>
                <span className="text-gray-400">
                  {expandedSections['acceptance'] ? <FaChevronUp /> : <FaChevronDown />}
                </span>
              </button>
              
              {expandedSections['acceptance'] && (
                <div className="p-4 space-y-3 text-gray-700 leading-relaxed animate-slideDown">
                  <div className="bg-red-50 rounded-lg p-4 border-l-4 border-red-500">
                    <p className="text-sm font-medium text-red-800">
                      ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
                    </p>
                  </div>
                  
                  <p>
                    By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by 
                    Glamorous Policies (including but not limited to Privacy Policy) as amended from time to time.
                  </p>
                </div>
              )}
            </div>

            {/* Section 3: Membership Eligibility */}
            <div className="border border-gray-200 rounded-xl overflow-hidden">
              <button
                onClick={() => toggleSection('membership')}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-1.5 bg-blue-100 rounded-lg">
                    <FaUsers className="text-blue-600" />
                  </div>
                  <h3 className="font-semibold text-gray-800">Membership Eligibility</h3>
                </div>
                <span className="text-gray-400">
                  {expandedSections['membership'] ? <FaChevronUp /> : <FaChevronDown />}
                </span>
              </button>
              
              {expandedSections['membership'] && (
                <div className="p-4 space-y-3 text-gray-700 leading-relaxed animate-slideDown">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                      <h4 className="font-semibold text-green-800 flex items-center gap-2">
                        <FaCheckCircle className="text-green-600" />
                        Eligible
                      </h4>
                      <ul className="text-sm text-green-700 space-y-1 mt-2">
                        <li>• Persons who can form legally binding contracts</li>
                        <li>• Adults (18 years and above)</li>
                        <li>• Persons with legal guardians (for minors)</li>
                      </ul>
                    </div>
                    <div className="bg-red-50 rounded-lg p-4 border border-red-200">
                      <h4 className="font-semibold text-red-800 flex items-center gap-2">
                        <FaInfoCircle className="text-red-600" />
                        Not Eligible
                      </h4>
                      <ul className="text-sm text-red-700 space-y-1 mt-2">
                        <li>• Minors without parental consent</li>
                        <li>• Un-discharged insolvents</li>
                        <li>• Persons incompetent to contract</li>
                      </ul>
                    </div>
                  </div>
                  
                  <div className="bg-amber-50 rounded-lg p-4 border border-amber-200">
                    <p className="text-sm text-amber-800">
                      <strong>For Minors:</strong> If you are a minor i.e. under the age of 18 years, you may use the 
                      Platform or access content on the Platform only under the supervision and prior consent/permission 
                      of a parent or legal guardian.
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Section 4: Account & Registration */}
            <div className="border border-gray-200 rounded-xl overflow-hidden">
              <button
                onClick={() => toggleSection('account')}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="p-1.5 bg-purple-100 rounded-lg">
                    <FaUserLock className="text-purple-600" />
                  </div>
                  <h3 className="font-semibold text-gray-800">Account & Registration</h3>
                </div>
                <span className="text-gray-400">
                  {expandedSections['account'] ? <FaChevronUp /> : <FaChevronDown />}
                </span>
              </button>
              
              {expandedSections['account'] && (
                <div className="p-4 space-y-3 text-gray-700 leading-relaxed animate-slideDown">
                  <div className="bg-gray-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 flex items-center gap-2">
                      <FaUserShield className="text-[#306D29]" />
                      Your Responsibilities
                    </h4>
                    <ul className="space-y-2 text-sm text-gray-600 mt-2">
                      <li className="flex items-start gap-2">
                        <FaCheckCircle className="text-green-500 mt-0.5 flex-shrink-0" />
                        <span>Maintain confidentiality of your Display Name and Password</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <FaCheckCircle className="text-green-500 mt-0.5 flex-shrink-0" />
                        <span>Keep your mobile number and email address up to date</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <FaCheckCircle className="text-green-500 mt-0.5 flex-shrink-0" />
                        <span>Log out from your account at the end of each session</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <FaCheckCircle className="text-green-500 mt-0.5 flex-shrink-0" />
                        <span>Immediately notify unauthorized use of your account</span>
                      </li>
                    </ul>
                  </div>

                  <div className="bg-red-50 rounded-lg p-4 border border-red-200">
                    <p className="text-sm text-red-800">
                      <strong>Important:</strong> You agree that Flipkart shall not be liable or responsible for 
                      the activities or consequences of use or misuse of any information that occurs under your 
                      Account in cases where You have failed to update Your revised mobile phone number and/or 
                      e-mail address on the Platform.
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Section 5: Key Points Summary */}
            <div className="bg-gradient-to-r from-[#306D29] to-[#4CAF50] rounded-2xl p-6 text-white">
              <h4 className="text-lg font-semibold mb-3 flex items-center gap-2">
                <FaGavel className="text-xl" />
                Key Points to Remember
              </h4>
              <div className="grid md:grid-cols-2 gap-3">
                <div className="flex items-start gap-2 bg-white/10 backdrop-blur-sm rounded-lg p-3">
                  <FaCheckCircle className="text-green-300 flex-shrink-0 mt-0.5" />
                  <span className="text-sm">Read terms carefully before using the platform</span>
                </div>
                <div className="flex items-start gap-2 bg-white/10 backdrop-blur-sm rounded-lg p-3">
                  <FaCheckCircle className="text-green-300 flex-shrink-0 mt-0.5" />
                  <span className="text-sm">Maintain account confidentiality</span>
                </div>
                <div className="flex items-start gap-2 bg-white/10 backdrop-blur-sm rounded-lg p-3">
                  <FaCheckCircle className="text-green-300 flex-shrink-0 mt-0.5" />
                  <span className="text-sm">Eligibility: Must be 18+ years old</span>
                </div>
                <div className="flex items-start gap-2 bg-white/10 backdrop-blur-sm rounded-lg p-3">
                  <FaCheckCircle className="text-green-300 flex-shrink-0 mt-0.5" />
                  <span className="text-sm">Keep contact information updated</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Need Help Section */}
        <div className="mt-8 bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-lg">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="p-3 bg-blue-100 rounded-full">
                <FaPhone className="text-blue-600 text-xl" />
              </div>
              <div>
                <h4 className="font-semibold text-gray-800">Need Help?</h4>
                <p className="text-sm text-gray-600">Our team is here to assist you</p>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
              <button className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition-all text-sm">
                <FaEnvelope /> Email Support
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-all text-sm">
                <FaWhatsapp /> WhatsApp
              </button>
              <Link to='/contact' className="flex items-center gap-2 px-4 py-2 bg-[#306D29] text-white rounded-lg hover:shadow-lg transition-all text-sm">
                Contact Us <FaArrowRight />
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Custom Animations */}
      <style jsx>{`
        @keyframes slideDown {
          from {
            opacity: 0;
            transform: translateY(-10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .animate-slideDown {
          animation: slideDown 0.3s ease-out;
        }
      `}</style>
    </div>
  );
};

export default TermOffUse;